### ISSUE TITLE
No link to the published paper from this repo

### ISSUE THREAD

**Issue by rigarash** [quantumbeam/materials-concept-learning#1]
This repo seems to contain the original implementation of [the paper](https://dx.doi.org/10.1088/2632-2153/aca23d) and there are links from the paper to this repo, but as far as I see, there is no link from this repo to the paper in README.md. The link to the published paper will ease scientists/developers who first find this repo.

**Comment by resnant** [comment]
Thank you for suggestion. I added citation. Thanks!
